#!/usr/bin/env python3
"""
docker_security.py — Docker Security Defaults generator and auditor.

Generates hardened Dockerfile snippets and audits existing Dockerfiles
for missing security directives.

Usage:
    python3 docker_security.py generate
    python3 docker_security.py audit <Dockerfile>
    python3 docker_security.py --test
"""

import json
import re
import sys
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Security directives catalogue
# ---------------------------------------------------------------------------

SECURITY_CHECKS: list[dict[str, Any]] = [
    {
        "id": "no-root-user",
        "description": "Container runs as non-root USER",
        "severity": "HIGH",
        "pattern": re.compile(r"^\s*USER\s+(?!root\b)(\S+)", re.MULTILINE),
        "negative_pattern": re.compile(r"^\s*USER\s+root\b", re.MULTILINE),
        "recommendation": (
            "Add 'RUN addgroup --system nonroot && adduser --system --ingroup nonroot nonroot' "
            "and 'USER nonroot' before the final CMD/ENTRYPOINT."
        ),
        "hardened_snippet": "USER nonroot",
    },
    {
        "id": "no-latest-tag",
        "description": "Base image pinned to a specific digest or tag (not :latest)",
        "severity": "MEDIUM",
        "pattern": re.compile(r"^\s*FROM\s+\S+(?<!:latest)\b", re.MULTILINE),
        "negative_pattern": re.compile(r"^\s*FROM\s+\S+:latest\b", re.MULTILINE),
        "recommendation": "Pin base images to a specific version tag or SHA digest.",
        "hardened_snippet": "FROM python:3.12-slim@sha256:<digest>",
    },
    {
        "id": "no-new-privileges",
        "description": "Security option 'no-new-privileges' set",
        "severity": "HIGH",
        "pattern": re.compile(r"no-new-privileges", re.MULTILINE),
        "negative_pattern": None,
        "recommendation": (
            "Pass '--security-opt=no-new-privileges:true' at runtime (docker run) "
            "or document it in your compose/helm values."
        ),
        "hardened_snippet": "# Runtime flag: --security-opt=no-new-privileges:true",
    },
    {
        "id": "cap-drop-all",
        "description": "All Linux capabilities dropped",
        "severity": "HIGH",
        "pattern": re.compile(r"--cap-drop[=\s]+ALL", re.MULTILINE | re.IGNORECASE),
        "negative_pattern": None,
        "recommendation": (
            "Pass '--cap-drop=ALL' at runtime and explicitly add back only required caps "
            "with '--cap-add=<CAP>'."
        ),
        "hardened_snippet": "# Runtime flag: --cap-drop=ALL --cap-add=NET_BIND_SERVICE",
    },
    {
        "id": "healthcheck-defined",
        "description": "HEALTHCHECK instruction present",
        "severity": "LOW",
        "pattern": re.compile(r"^\s*HEALTHCHECK\b", re.MULTILINE),
        "negative_pattern": None,
        "recommendation": "Add a HEALTHCHECK so orchestrators can detect unhealthy containers.",
        "hardened_snippet": (
            "HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\\n"
            "    CMD curl -f http://localhost:8080/health || exit 1"
        ),
    },
    {
        "id": "no-add-instruction",
        "description": "ADD replaced with COPY (ADD can fetch remote URLs)",
        "severity": "MEDIUM",
        "pattern": None,  # absence of ADD is the good state
        "negative_pattern": re.compile(r"^\s*ADD\s+http", re.MULTILINE),
        "recommendation": "Use COPY instead of ADD. If you need remote files, fetch them explicitly with RUN curl.",
        "hardened_snippet": "# Use COPY instead of ADD for local files",
    },
    {
        "id": "read-only-root",
        "description": "Read-only root filesystem",
        "severity": "MEDIUM",
        "pattern": re.compile(r"--read-only", re.MULTILINE),
        "negative_pattern": None,
        "recommendation": "Pass '--read-only' at runtime and mount writable volumes for /tmp and app data.",
        "hardened_snippet": "# Runtime flag: --read-only --tmpfs /tmp",
    },
]


# ---------------------------------------------------------------------------
# Hardened Dockerfile template
# ---------------------------------------------------------------------------

HARDENED_TEMPLATE = """\
# ---------------------------------------------------------------------------
# Hardened Dockerfile template (generated by docker_security.py)
# Replace <APP_IMAGE>, <APP_VERSION>, <port>, and app-specific steps.
# ---------------------------------------------------------------------------

# ── Stage 1: build ──────────────────────────────────────────────────────────
FROM <APP_IMAGE>:<APP_VERSION> AS builder
WORKDIR /app

# Install deps as root in build stage
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# ── Stage 2: runtime ────────────────────────────────────────────────────────
FROM python:3.12-slim AS runtime

# Create non-root user
RUN addgroup --system nonroot \\
 && adduser --system --ingroup nonroot --no-create-home nonroot

WORKDIR /app

# Copy only the installed artefacts from builder
COPY --from=builder --chown=nonroot:nonroot /app /app

# Drop to non-root
USER nonroot

# Expose app port (document only; actual binding is at runtime)
EXPOSE <port>

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
    CMD curl -f http://localhost:<port>/health || exit 1

# ── Runtime security flags (add to your docker run / compose / helm) ────────
# --cap-drop=ALL
# --cap-add=NET_BIND_SERVICE          # add only what's needed
# --security-opt=no-new-privileges:true
# --read-only
# --tmpfs /tmp

ENTRYPOINT ["python3", "-m", "app"]
"""


# ---------------------------------------------------------------------------
# Core audit logic
# ---------------------------------------------------------------------------

def audit_dockerfile(dockerfile_path: str) -> dict[str, Any]:
    """
    Audit an existing Dockerfile and return a structured report.

    Parameters
    ----------
    dockerfile_path:
        Path to the Dockerfile to audit.

    Returns
    -------
    dict with keys: path, passed, failed, warnings, findings
    """
    content = Path(dockerfile_path).read_text(encoding="utf-8", errors="replace")

    findings: list[dict[str, Any]] = []
    passed: list[str] = []
    failed: list[str] = []

    for check in SECURITY_CHECKS:
        check_id = check["id"]
        present = False

        if check["negative_pattern"] is not None:
            # The check FAILS if the negative pattern is found
            if check["negative_pattern"].search(content):
                findings.append({
                    "check": check_id,
                    "description": check["description"],
                    "severity": check["severity"],
                    "status": "FAIL",
                    "recommendation": check["recommendation"],
                    "snippet": check.get("hardened_snippet"),
                })
                failed.append(check_id)
                continue

        if check["pattern"] is not None:
            present = bool(check["pattern"].search(content))
        else:
            # No positive pattern means we only care about absence of negative
            present = True

        if present:
            passed.append(check_id)
        else:
            findings.append({
                "check": check_id,
                "description": check["description"],
                "severity": check["severity"],
                "status": "MISSING",
                "recommendation": check["recommendation"],
                "snippet": check.get("hardened_snippet"),
            })
            failed.append(check_id)

    return {
        "path": dockerfile_path,
        "passed": passed,
        "failed": failed,
        "total_checks": len(SECURITY_CHECKS),
        "pass_count": len(passed),
        "fail_count": len(failed),
        "findings": findings,
    }


def generate_hardened_dockerfile() -> str:
    """Return the hardened Dockerfile template string."""
    return HARDENED_TEMPLATE


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

INSECURE_DOCKERFILE = """\
FROM ubuntu:latest
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
ADD http://example.com/config.json /app/config.json
CMD ["python", "app.py"]
"""

SECURE_DOCKERFILE = """\
FROM python:3.12-slim
WORKDIR /app
RUN addgroup --system nonroot && adduser --system --ingroup nonroot nonroot
COPY --chown=nonroot:nonroot . .
RUN pip install --no-cache-dir -r requirements.txt
USER nonroot
HEALTHCHECK --interval=30s CMD curl -f http://localhost:8080/ || exit 1
# --cap-drop=ALL --security-opt=no-new-privileges:true --read-only
CMD ["python", "app.py"]
"""


def run_tests() -> None:
    """Self-test: validate audit against secure and insecure sample Dockerfiles."""
    import tempfile, os

    print("Running docker_security self-tests...")

    with tempfile.TemporaryDirectory() as tmpdir:
        insecure_path = os.path.join(tmpdir, "Dockerfile.insecure")
        secure_path = os.path.join(tmpdir, "Dockerfile.secure")
        Path(insecure_path).write_text(INSECURE_DOCKERFILE)
        Path(secure_path).write_text(SECURE_DOCKERFILE)

        insecure_report = audit_dockerfile(insecure_path)
        secure_report = audit_dockerfile(secure_path)

    print(f"  Insecure Dockerfile — failed checks: {insecure_report['fail_count']} (expected ≥4)")
    assert insecure_report["fail_count"] >= 4, (
        f"Expected ≥4 failures for insecure Dockerfile, got {insecure_report['fail_count']}"
    )

    insecure_ids = {f["check"] for f in insecure_report["findings"]}
    for expected_id in ("no-root-user", "no-latest-tag", "no-new-privileges", "cap-drop-all"):
        assert expected_id in insecure_ids, f"Expected check '{expected_id}' to fail on insecure Dockerfile"

    print(f"  Secure Dockerfile  — failed checks: {secure_report['fail_count']} (expected ≤2)")
    assert secure_report["fail_count"] <= 2, (
        f"Secure Dockerfile should have ≤2 failures, got {secure_report['fail_count']}: "
        f"{[f['check'] for f in secure_report['findings']]}"
    )

    # Generate test
    template = generate_hardened_dockerfile()
    assert "USER nonroot" in template
    assert "--cap-drop=ALL" in template
    assert "--security-opt=no-new-privileges" in template
    assert "HEALTHCHECK" in template

    print("  All tests PASSED ✓")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    """Entry point."""
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    cmd = sys.argv[1]

    if cmd == "--test":
        run_tests()
        return

    if cmd == "generate":
        print(generate_hardened_dockerfile())
        return

    if cmd == "audit":
        if len(sys.argv) < 3:
            print("Usage: python3 docker_security.py audit <Dockerfile>", file=sys.stderr)
            sys.exit(1)
        dockerfile = sys.argv[2]
        if not Path(dockerfile).is_file():
            print(f"Error: '{dockerfile}' not found.", file=sys.stderr)
            sys.exit(1)
        report = audit_dockerfile(dockerfile)
        print(json.dumps(report, indent=2))
        return

    print(f"Unknown command: {cmd}", file=sys.stderr)
    print(__doc__)
    sys.exit(1)


if __name__ == "__main__":
    main()
